src/Entity/Activity.php
<?php

namespace App\Entity;

use App\Repository\ActivityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

#[ApiResource(

    collectionOperations: [
        'get'=>[
            'normalization_context'=> ['groups'=>[ 'read:activities:collection']]
        ],
        'post' =>[
            'denormalization_context'=> ['groups'=>['activity:write']],
        ],
        
    ],
    itemOperations: [
        'put',
        'delete',
        'get',
    ],

    normalizationContext: ['groups' => 'activity:read'],
)]
#[ORM\Entity(repositoryClass: ActivityRepository::class)]
class Activity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(["user:read"])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $company = null;

    #[ORM\Column(length: 255)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $schedule = null;

    #[ORM\Column]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?int $duration = null;

    #[ORM\ManyToOne(cascade:["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?Unit $unit = null;

    #[ORM\Column(length: 255)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $country = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?\DateTimeInterface $published_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?int $price = null;

    #[ORM\Column(length: 255)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(["user:read", "activity:write", 'read:activities:collection'])]
    private ?string $short_description = null;

    #[ORM\ManyToOne(inversedBy: 'activities')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(["activity:write", 'read:activities:collection'])]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: Review::class)]
    private Collection $reviews;

    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: Features::class)]
    #[Groups(["activity:write", 'read:activities:collection'])]
    private Collection $features;
    
    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->features = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getSchedule(): ?string
    {
        return $this->schedule;
    }

    public function setSchedule(?string $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getUnit(): ?Unit
    {
        return $this->unit;
    }

    public function setUnit(?Unit $unit): self
    {
        $this->unit = $unit;

        return $this;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setActivity($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getActivity() === $this) {
                $review->setActivity(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Features>
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Features $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features->add($feature);
            $feature->setActivity($this);
        }

        return $this;
    }

    public function removeFeature(Features $feature): self
    {
        if ($this->features->removeElement($feature)) {
            // set the owning side to null (unless already changed)
            if ($feature->getActivity() === $this) {
                $feature->setActivity(null);
            }
        }

        return $this;
    }

    // Admin : get unit type when adding an activity
    public function __toString()
    {
        return $this->name;
    }
}

src/Form/ActivityType.php
<?php

namespace App\Form;

use App\Entity\Activity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActivityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('company')
            ->add('address')
            ->add('phone_number')
            ->add('schedule')
            ->add('duration')
            ->add('name')
            ->add('city')
            ->add('country')
            ->add('published_at')
            ->add('picture')
            ->add('price')
            ->add('description')
            ->add('short_description')
            ->add('unit')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Activity::class,
        ]);
    }
}

src/Controller/ActivityController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Form\ActivityType;
use App\Repository\ActivityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/activity')]
class ActivityController extends AbstractController
{
    #[Route('/', name: 'app_activity_index', methods: ['GET'])]
    public function index(ActivityRepository $activityRepository): Response
    {
        return $this->render('activity/index.html.twig', [
            'activities' => $activityRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_activity_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ActivityRepository $activityRepository): Response
    {
        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $activityRepository->add($activity, true);

            return $this->redirectToRoute('app_activity_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('activity/new.html.twig', [
            'activity' => $activity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_activity_show', methods: ['GET'])]
    public function show(Activity $activity): Response
    {
        return $this->render('activity/show.html.twig', [
            'activity' => $activity,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_activity_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Activity $activity, ActivityRepository $activityRepository): Response
    {
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $activityRepository->add($activity, true);

            return $this->redirectToRoute('app_activity_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('activity/edit.html.twig', [
            'activity' => $activity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_activity_delete', methods: ['POST'])]
    public function delete(Request $request, Activity $activity, ActivityRepository $activityRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$activity->getId(), $request->request->get('_token'))) {
            $activityRepository->remove($activity, true);
        }

        return $this->redirectToRoute('app_activity_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/activity/_delete_form.html.twig
<form method="post" action="{{ path('app_activity_delete', {'id': activity.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activity.id) }}">
    <button class="btn">Delete</button>
</form>

templates/activity/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/activity/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Activity{% endblock %}

{% block body %}
    <h1>Edit Activity</h1>

    {{ include('activity/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_activity_index') }}">back to list</a>

    {{ include('activity/_delete_form.html.twig') }}
{% endblock %}

templates/activity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity index{% endblock %}

{% block body %}
    <h1>Activity index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Company</th>
                <th>Address</th>
                <th>Phone_number</th>
                <th>Schedule</th>
                <th>Duration</th>
                <th>Name</th>
                <th>City</th>
                <th>Country</th>
                <th>Published_at</th>
                <th>Picture</th>
                <th>Price</th>
                <th>Description</th>
                <th>Short_description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for activity in activities %}
            <tr>
                <td>{{ activity.id }}</td>
                <td>{{ activity.company }}</td>
                <td>{{ activity.address }}</td>
                <td>{{ activity.phoneNumber }}</td>
                <td>{{ activity.schedule }}</td>
                <td>{{ activity.duration }}</td>
                <td>{{ activity.name }}</td>
                <td>{{ activity.city }}</td>
                <td>{{ activity.country }}</td>
                <td>{{ activity.publishedAt ? activity.publishedAt|date('Y-m-d') : '' }}</td>
                <td>{{ activity.picture }}</td>
                <td>{{ activity.price }}</td>
                <td>{{ activity.description }}</td>
                <td>{{ activity.shortDescription }}</td>
                <td>
                    <a href="{{ path('app_activity_show', {'id': activity.id}) }}">show</a>
                    <a href="{{ path('app_activity_edit', {'id': activity.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_activity_new') }}">Create new</a>
{% endblock %}

templates/activity/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Activity{% endblock %}

{% block body %}
    <h1>Create new Activity</h1>

    {{ include('activity/_form.html.twig') }}

    <a href="{{ path('app_activity_index') }}">back to list</a>
{% endblock %}

templates/activity/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity{% endblock %}

{% block body %}
    <h1>Activity</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ activity.id }}</td>
            </tr>
            <tr>
                <th>Company</th>
                <td>{{ activity.company }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ activity.address }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ activity.phoneNumber }}</td>
            </tr>
            <tr>
                <th>Schedule</th>
                <td>{{ activity.schedule }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ activity.duration }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ activity.name }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ activity.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ activity.country }}</td>
            </tr>
            <tr>
                <th>Published_at</th>
                <td>{{ activity.publishedAt ? activity.publishedAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ activity.picture }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ activity.price }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ activity.description }}</td>
            </tr>
            <tr>
                <th>Short_description</th>
                <td>{{ activity.shortDescription }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_activity_index') }}">back to list</a>

    <a href="{{ path('app_activity_edit', {'id': activity.id}) }}">edit</a>

    {{ include('activity/_delete_form.html.twig') }}
{% endblock %}