src/Entity/Review.php
<?php

namespace App\Entity;

use App\Repository\ReviewRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

#[ApiResource()]
#[ORM\Entity(repositoryClass: ReviewRepository::class)]
class Review
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $rate = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 600)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $posted_at = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'reviews')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Activity $activity = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(int $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPostedAt(): ?\DateTimeInterface
    {
        return $this->posted_at;
    }

    public function setPostedAt(\DateTimeInterface $posted_at): self
    {
        $this->posted_at = $posted_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getActivity(): ?Activity
    {
        return $this->activity;
    }

    public function setActivity(?Activity $activity): self
    {
        $this->activity = $activity;

        return $this;
    }
}

src/Form/ReviewType.php
<?php

namespace App\Form;

use App\Entity\Review;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReviewType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('rate')
            ->add('title')
            ->add('description')
            ->add('picture')
            ->add('posted_at')
            ->add('user')
            ->add('activity')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Review::class,
        ]);
    }
}

src/Controller/ReviewController.php
<?php

namespace App\Controller;

use App\Entity\Review;
use App\Form\ReviewType;
use App\Repository\ReviewRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/review')]
class ReviewController extends AbstractController
{
    #[Route('/', name: 'app_review_index', methods: ['GET'])]
    public function index(ReviewRepository $reviewRepository): Response
    {
        return $this->render('review/index.html.twig', [
            'reviews' => $reviewRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_review_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReviewRepository $reviewRepository): Response
    {
        $review = new Review();
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reviewRepository->add($review, true);

            return $this->redirectToRoute('app_review_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('review/new.html.twig', [
            'review' => $review,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_review_show', methods: ['GET'])]
    public function show(Review $review): Response
    {
        return $this->render('review/show.html.twig', [
            'review' => $review,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_review_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Review $review, ReviewRepository $reviewRepository): Response
    {
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reviewRepository->add($review, true);

            return $this->redirectToRoute('app_review_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('review/edit.html.twig', [
            'review' => $review,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_review_delete', methods: ['POST'])]
    public function delete(Request $request, Review $review, ReviewRepository $reviewRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$review->getId(), $request->request->get('_token'))) {
            $reviewRepository->remove($review, true);
        }

        return $this->redirectToRoute('app_review_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/review/_delete_form.html.twig
<form method="post" action="{{ path('app_review_delete', {'id': review.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ review.id) }}">
    <button class="btn">Delete</button>
</form>

templates/review/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/review/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Review{% endblock %}

{% block body %}
    <h1>Edit Review</h1>

    {{ include('review/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_review_index') }}">back to list</a>

    {{ include('review/_delete_form.html.twig') }}
{% endblock %}

templates/review/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review index{% endblock %}

{% block body %}
    <h1>Review index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Rate</th>
                <th>Title</th>
                <th>Description</th>
                <th>Picture</th>
                <th>Posted_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for review in reviews %}
            <tr>
                <td>{{ review.id }}</td>
                <td>{{ review.rate }}</td>
                <td>{{ review.title }}</td>
                <td>{{ review.description }}</td>
                <td>{{ review.picture }}</td>
                <td>{{ review.postedAt ? review.postedAt|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_review_show', {'id': review.id}) }}">show</a>
                    <a href="{{ path('app_review_edit', {'id': review.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_review_new') }}">Create new</a>
{% endblock %}

templates/review/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Review{% endblock %}

{% block body %}
    <h1>Create new Review</h1>

    {{ include('review/_form.html.twig') }}

    <a href="{{ path('app_review_index') }}">back to list</a>
{% endblock %}

templates/review/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review{% endblock %}

{% block body %}
    <h1>Review</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ review.id }}</td>
            </tr>
            <tr>
                <th>Rate</th>
                <td>{{ review.rate }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ review.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ review.description }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ review.picture }}</td>
            </tr>
            <tr>
                <th>Posted_at</th>
                <td>{{ review.postedAt ? review.postedAt|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_review_index') }}">back to list</a>

    <a href="{{ path('app_review_edit', {'id': review.id}) }}">edit</a>

    {{ include('review/_delete_form.html.twig') }}
{% endblock %}